# Generated by Django 5.2.4 on 2025-07-26 05:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplateform_wactchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='wactchlist',
            name='plateform',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplateform'),
            preserve_default=False,
        ),
    ]
