# Generated by Django 5.2.4 on 2025-07-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_wactchlist_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wactchlist',
            name='plateform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplateform'),
        ),
    ]
