# Generated by Django 5.2.4 on 2025-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=150)),
            ],
        ),
    ]
